name: CI via Docker
on:
  pull_request:
    branches:
      - master
jobs:
  build-ci:
    runs-on: ubuntu-latest
    environment: ci
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: thibautarnoux/laravel-summoner-tracking
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/ci/Dockerfile
          tags: thibautarnoux/laravel-summoner-tracking:ci
          labels: ${{ steps.meta.outputs.labels }}
          push: true
  run-ci:
    runs-on: ubuntu-latest
    container:
      image: thibautarnoux/laravel-summoner-tracking:ci
      env:
        APP_KEY: ${{ secrets.APP_KEY }}
    defaults:
      run:
        working-directory: /var/www/html
    steps:
      - name: Lint
        run: ./vendor/bin/pint
