name: Deployment
on:
  workflow_dispatch:
  # Wait for automatic deployment
  # push:
  #   branches:
  #     - main
jobs:
  changelog:
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: write
    steps:
      - name: Conventional Changelog Action
        uses: TriPSs/conventional-changelog-action@v5
        with:
          github-token: ${{ github.token }}
          skip-git-pull: 'true'
          skip-version-file: 'true'
          skip-bump: 'true'
      # TODO : Generate a github release ?
  build:
    needs: changelog
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Docker Apache meta
        id: apache-meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ vars.DOCKERHUB_USERNAME }}/${{ vars.DOCKERHUB_REPOSITORY_APACHE }}
      - name: Build and push Apache
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/production/apache2/Dockerfile
          tags: ${{ steps.apache-meta.outputs.tags }}
          labels: ${{ steps.apache-meta.outputs.labels }}
          push: true
      - name: Docker App meta
        id: app-meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ vars.DOCKERHUB_USERNAME }}/${{ vars.DOCKERHUB_REPOSITORY }}
      - name: Build and push App
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/production/php/Dockerfile
          tags: ${{ steps.app-meta.outputs.tags }}
          labels: ${{ steps.app-meta.outputs.labels }}
          push: true
