name: Deployment
on:
  # TODO : remove after debug
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Get code
        uses: actions/checkout@v3
      # TODO : build docker images
