name: Test
on:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Test on environment production
        run: echo "Test on environment production"
